### PR TITLE
fix(sharding): sharding guide overhaul

### LINKED ISSUE #620: "message" event moved to individual shards
https://discordjs.guide/sharding/additional-information.html#shard-messages (and possibly other subsections) need updating since the "message" event [moved to individual shards](https://discordjs.guide/additional-info/changes-in-v12.html#shardingmanager-message).

### PR DESCRIPTION
**Pull request by Lewdcario**
**Please describe the changes this PR makes and why it should be merged:**

Fixes #620 and improves on the practices in the code a bit.

### CODE REVIEW

File: code-samples/sharding/extended/11/bot.js [hunk 1]
```diff
@@ -50,19 +45,13 @@ client.on('message', message => {
...
 				const foundEmoji = emojiArray.find(emoji => emoji);
 				if (!foundEmoji) return message.reply('I could not find such an emoji.');
-
-				return client.rest.makeRequest('get', Discord.Constants.Endpoints.Guild(foundEmoji.guild).toString(), true)
-					.then(raw => {
-						const guild = new Discord.Guild(client, raw);
-						const emoji = new Discord.Emoji(guild, foundEmoji);
-						return message.reply(`I have found an emoji ${emoji.toString()}!`);
-					});
+				return message.reply(`I have found the emoji ${foundEmoji.id ? `<${foundEmoji.animated ? 'a' : ''}:${foundEmoji.name}:${foundEmoji.id}>` : foundEmoji.name}!`);
```
Comment (Danktuary) [inline code-samples/sharding/extended/11/bot.js:54]:
```suggestion
				return message.reply(`I have found the ${foundEmoji.id ? `<${foundEmoji.animated ? 'a' : ''}:${foundEmoji.name}:${foundEmoji.id}>` : foundEmoji.name} emoji!`);
```

File: code-samples/sharding/extended/12/bot.js [hunk 2]
```diff
@@ -2,14 +2,9 @@ const Discord = require('discord.js');
...
-	if (!temp) return null;
-
-	const emoji = Object.assign({}, temp);
-	if (emoji.guild) emoji.guild = emoji.guild.id;
-	emoji.require_colons = emoji.requiresColons;
-
+function findEmoji(nameOrID) {
+	const emoji = this.emojis.cache.get(nameOrID) || this.emojis.cache.find(e => e.name.toLowerCase() === nameOrID.toLowerCase());
+	if (!emoji) return null;
 	return emoji;
```
Comment (Danktuary) [inline code-samples/sharding/extended/12/bot.js:8]:
```suggestion
	return this.emojis.cache.get(nameOrID) || this.emojis.cache.find(e => e.name.toLowerCase() === nameOrID.toLowerCase());
```

File: code-samples/sharding/extended/12/bot.js [hunk 3]
```diff
@@ -50,19 +45,13 @@ client.on('message', message => {
...
 				const foundEmoji = emojiArray.find(emoji => emoji);
 				if (!foundEmoji) return message.reply('I could not find such an emoji.');
-
-				return client.api.guilds(foundEmoji.guild).get()
-					.then(raw => {
-						const guild = new Discord.Guild(client, raw);
-						const emoji = new Discord.GuildEmoji(client, foundEmoji, guild);
-						return message.reply(`I have found an emoji ${emoji.toString()}!`);
-					});
+				return message.reply(`I have found the emoji ${foundEmoji.animated ? `<${foundEmoji.identifier}>` : `<:${foundEmoji.identifier}>`}!`);
```
Comment (Danktuary) [inline code-samples/sharding/extended/12/bot.js:54]:
```suggestion
				return message.reply(`I have found the ${foundEmoji.animated ? `<${foundEmoji.identifier}>` : `<:${foundEmoji.identifier}>`} emoji!`);
```

File: guide/sharding/additional-information.md [hunk 4]
```diff
@@ -13,14 +13,34 @@ Here are some extra topics covered about sharding that might have raised concern
...
+
+```js
+manager.spawn()
+	.then(shards => {
+		shards.forEach(shard => {
+			shard.on('message', message => {
+				console.log(`Shard[${shard.id}] : ${message._eval} : ${message._result}`);
+			});
+		});
+	});
```
Comment (Danktuary) [inline guide/sharding/additional-information.md:39]:
```suggestion
	})
	.catch(console.error);
```

File: guide/sharding/extended.md [hunk 5]
```diff
@@ -217,8 +217,8 @@ Let's start with a basic function, which will try to grab an emoji from the curr
 <branch version="11.x">
 
 ```js
-function findEmoji(id) {
-	const emoji = this.emojis.get(id);
+function findEmoji(nameOrID) {
+	const emoji = this.emojis.get(query) || this.emojis.find(e => e.name.toLowerCase() === nameOrID.toLowerCase());
 	if (!emoji) return null;
 	return emoji;
```
Comment (Danktuary) [inline guide/sharding/extended.md:223]:
```suggestion
	return this.emojis.get(nameOrID) || this.emojis.find(e => e.name.toLowerCase() === nameOrID.toLowerCase());
```

File: guide/sharding/extended.md [hunk 6]
```diff
@@ -228,8 +228,8 @@ function findEmoji(id) {
 <branch version="12.x">
 
 ```js
-function findEmoji(id) {
-	const emoji = this.emojis.cache.get(id);
+function findEmoji(nameOrID) {
+	const emoji = this.emojis.cache.get(nameOrID) || this.emojis.cache.find(e => e.name.toLowerCase() === nameOrID.toLowerCase());
 	if (!emoji) return null;
 	return emoji;
```
Comment (Danktuary) [inline guide/sharding/extended.md:234]:
```suggestion
	return this.emojis.cache.get(nameOrID) || this.emojis.cache.find(e => e.name.toLowerCase() === nameOrID.toLowerCase());
```

File: guide/sharding/extended.md [hunk 7]
```diff
@@ -285,52 +285,37 @@ Now, run this code, and you will surely get a result that looks like the followi
...
-+   // Circular references can't be returned outside of eval, so change it to the id
-+   if (emoji.guild) emoji.guild = emoji.guild.id;
-+   // A new object will be constructed, so simulate raw data by adding this property back
-+   emoji.require_colons = emoji.requiresColons;
-+
+```js
+function findEmoji(nameOrID) {
+	const emoji = this.emojis.get(nameOrID) || this.emojis.find(e => e.name.toLowerCase() === nameOrID.toLowerCase());
+	if (!emoji) return null;
+	// If you wanted to delete the emoji with Discord.js, this is where you would do it. Otherwise, don't include this code.
```
Comment (Danktuary) [inline guide/sharding/extended.md:296]:
```suggestion
	if (!emoji) return;
	// If you wanted to delete the emoji with discord.js, this is where you would do it. Otherwise, don't include this code.
```

File: guide/sharding/extended.md [hunk 8]
```diff
@@ -285,52 +285,37 @@ Now, run this code, and you will surely get a result that looks like the followi
...
-+   // Circular references can't be returned outside of eval, so change it to the id
-+   if (emoji.guild) emoji.guild = emoji.guild.id;
-+   // A new object will be constructed, so simulate raw data by adding this property back
-+   emoji.require_colons = emoji.requiresColons;
-+
+```js
+function findEmoji(nameOrID) {
+	const emoji = this.emojis.cache.get(nameOrID) || this.emojis.cache.find(e => e.name.toLowerCase() === nameOrID.toLowerCase());
+	if (!emoji) return null;
+	// If you wanted to delete the emoji with Discord.js, this is where you would do it. Otherwise, don't include this code.
```
Comment (Danktuary) [inline guide/sharding/extended.md:310]:
```suggestion
	if (!emoji) return;
	// If you wanted to delete the emoji with discord.js, this is where you would do it. Otherwise, don't include this code.
```

File: guide/sharding/extended.md [hunk 9]
```diff
@@ -285,52 +285,37 @@ Now, run this code, and you will surely get a result that looks like the followi
...
+	emoji.delete();
 	return emoji;
 }
 ```
 
 </branch>
 
-Now, you will want to make use of it in the actual command:
+WIth all that said and done, usually we want to display the result, so here is how we can go about doing that:
```
Comment (Danktuary) [inline guide/sharding/extended.md:318]:
```suggestion
With all that said and done, you'll usually want to display the result, so here is how you can go about doing that:
```

File: guide/sharding/extended.md [hunk 10]
```diff
@@ -341,16 +326,7 @@ Now, you will want to make use of it in the actual command:
...
-+           // Acquire a guild that can be reconstructed with discord.js
-+           return client.rest.makeRequest('get', Discord.Constants.Endpoints.Guild(foundEmoji.guild).toString(), true)
-+                   .then(raw => {
-+                       // Reconstruct a guild
-+                       const guild = new Discord.Guild(client, raw);
-+                       // Reconstruct an emoji object as required by discord.js
-+                       const emoji = new Discord.Emoji(guild, foundEmoji);
-+                       return message.reply(`I have found an emoji ${emoji.toString()}!`);
-+                   });
++           return message.reply(`I have found the emoji ${foundEmoji.id ? `<${foundEmoji.animated ? 'a' : ''}:${foundEmoji.name}:${foundEmoji.id}>` : foundEmoji.name}!`);
```
Comment (Danktuary) [inline guide/sharding/extended.md:329]:
```suggestion
+           return message.reply(`I have found the ${foundEmoji.id ? `<${foundEmoji.animated ? 'a' : ''}:${foundEmoji.name}:${foundEmoji.id}>` : foundEmoji.name} emoji!`);
```

File: guide/sharding/extended.md [hunk 11]
```diff
@@ -364,16 +340,7 @@ Now, you will want to make use of it in the actual command:
...
-+           // Acquire a guild that can be reconstructed with discord.js
-+           return client.api.guilds(foundEmoji.guild).get()
-+                   .then(raw => {
-+                       // Reconstruct a guild
-+                       const guild = new Discord.Guild(client, raw);
-+                       // Reconstruct an emoji object as required by discord.js
-+                       const emoji = new Discord.GuildEmoji(client, foundEmoji, guild);
-+                       return message.reply(`I have found an emoji ${emoji.toString()}!`);
-+                   });
++           return message.reply(`I have found the emoji ${foundEmoji.animated ? `<${foundEmoji.identifier}>` : `<:${foundEmoji.identifier}>`}!`);
```
Comment (Danktuary) [inline guide/sharding/extended.md:343]:
```suggestion
+           return message.reply(`I have found the ${foundEmoji.animated ? `<${foundEmoji.identifier}>` : `<:${foundEmoji.identifier}>`} emoji!`);
```
